export {CreateWishlistRequest as CreateWishlistRequestSchema} from '../../../generated/schemas'
export type {CreateWishlistRequest as CreateWishlistBody} from '../../../generated/schemas'
export {UpdateWishlistRequest as UpdateWishlistRequestSchema} from '../../../generated/schemas'
export type {UpdateWishlistRequest as UpdateWishlistBody} from '../../../generated/schemas'
export {AddItemToWishlistRequest as AddItemToWishlistRequestSchema} from '../../../generated/schemas'
export type {AddItemToWishlistRequest as AddItemToWishlistBody} from '../../../generated/schemas'
export {ListWishlistsQuery as ListWishlistsQuerySchema} from '../../../generated/schemas'
export {RetrieveWishlistQuery as RetrieveWishlistQuerySchema} from '../../../generated/schemas'
