export {CreateWishlistRequest as CreateWishlistRequestSchema} from '../../../generated/schemas'
export type {CreateWishlistRequest} from '../../../generated/schemas'
export {UpdateWishlistRequest as UpdateWishlistRequestSchema} from '../../../generated/schemas'
export type {UpdateWishlistRequest} from '../../../generated/schemas'
export {AddWishlistItemRequest as AddWishlistItemRequestSchema} from '../../../generated/schemas'
export type {AddWishlistItemRequest} from '../../../generated/schemas'
